#!/usr/bin/env bash

# Any branches on this list will be ignored, and the messages will not be standardized.
QUIET_BRANCHES='HEAD|master|production|staging'

# Commit messages that do not respect the minimum length are rejected.
MIN_LENGTH=10

# Nothing to do, branch is on the quiet list.
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
if echo "$BRANCH_NAME" | grep --quiet -E "$QUIET_BRANCHES"; then
    echo -e "[\033[0;34mINFO\033[0m] Your branch is in the quiet list or in an unknown state, the message will not be edited."
    exit 0
fi

# Check if the branch name conforms with the standard.
BRANCH_NAME=$(echo "$BRANCH_NAME" | grep -Eoi "^[a-z]+\-[0-9]+" | tr "[a-z]" "[A-Z]")
if [ -z "$BRANCH_NAME" ]; then
    echo -e "[\033[0;34mINFO\033[0m] Your branch name does not conform to the standard, the message will not be edited."
    exit 0
fi

# Check minimum length constraints.
MESSAGE=$(cat $1 | sed "s/^[ \t]*//;s/[ \t]*$//" | tr -s " " | sed "s/[^[:punct:]]$/&./")
if [ ${#MESSAGE} -lt $MIN_LENGTH ]; then
    echo -e "[\033[0;31mFAILURE\033[0m] Your commit message must be at least $MIN_LENGTH characters long."
    exit 1
fi

# Build the message name.
MESSAGE="$BRANCH_NAME $(echo ${MESSAGE:0:1} | tr \"[a-z]\" \"[A-Z]\")${MESSAGE:1}"

# Replace the message.
echo "$MESSAGE" > $1
